package main

import (
	"encoding/json"
	"github.com/yekongxingle/discord-chatbot/pkg/resStruct"
	"github.com/yekongxingle/discord-chatbot/pkg/setting"
	"github.com/yekongxingle/discord-chatbot/pkg/utils"
	"log"
	"time"
)

func main() {
	//1、初始化配置
	setting.InitConfig()
	//2、进入循环
	for {
		//	2.1、获得页面数据
		bytes := utils.Get_context(setting.Conf.Chaturl)
		res:=resStruct.AutoGenerated{}
		err := json.Unmarshal(bytes, &res)
		if err != nil {
			log.Println(err)
		}
		//	2.2、检查是否给cue，被cue则退出
		err = utils.CheckSafe(res)
		if err != nil {
			log.Fatal(err)

		}
		//2.3、未被cue，从页面中的数据复制，发送消息
		utils.PostMessage(res)
		time.Sleep(10*time.Second)
	}



}
